name: Deploy Quartz site to GitHub Pages
 
on: push
 
permissions:
  contents: read
  pages: write
  id-token: write
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'jackyzha0'
          repository: 'quartz'
