name: Deploy Quartz site to GitHub Pages
 
on: push
 
permissions:
  contents: read
  pages: write
  id-token: write
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Quartz
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'v4'
          owner: 'jackyzha0'
          repository: 'quartz'
      - name: Clone data files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - name: install quartz
        run: |
          ls
          cd quartz
          npm i
          npx quartz build
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
